version: '3.8'

services:
  npc-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: npc-website
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      # SSL certificates (uncomment when ready)
      # - ./ssl:/etc/nginx/ssl:ro
      # Logs
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - npc-network

  # Optional: Add a database backup service
  # db-backup:
  #   image: postgres:15-alpine
  #   environment:
  #     - PGPASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - ./backups:/backups
  #   command: >
  #     sh -c "
  #       while true; do
  #         pg_dump -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} > /backups/backup_$(date +%Y%m%d_%H%M%S).sql
  #         sleep 86400
  #       done
  #     "
  #   restart: unless-stopped
  #   networks:
  #     - npc-network

networks:
  npc-network:
    driver: bridge

volumes:
  nginx-logs: